### ISSUE TITLE
ReferenceError: require is not defined - after building the project

### ISSUE THREAD

**Issue by kasapvictor** [Faire/mjml-react#96]
This issue is continuation of [previews #93](https://github.com/Faire/mjml-react/issues/93) 

![Google Chrome2023-02-24 at 11 04 10](https://user-images.githubusercontent.com/73124371/221163701-7d2b5cbd-fa6a-4a2c-af99-068facbde275.png)

So, we've solved 'process' problem, and after building the project and running the via browser-sync from `./dist` I get new error

```
Uncaught ReferenceError: require is not defined
    at index-058953bb.js:40:57774
```

Actually to get this error you can just add this import and nothing else

![PhpStorm2023-02-24 at 11 22 47@2x](https://user-images.githubusercontent.com/73124371/221167360-33bc057a-1168-4ddf-8b9d-3d5c80a12d8c.png)

First Screen - `npm run dev`
Second Screen - `browser-sync ./dist`

![Google Chrome2023-02-24 at 12 39 11](https://user-images.githubusercontent.com/73124371/221181181-19dd826f-afeb-4136-93ce-8ebd7e28bd1c.gif)

**Comment by IanEdington** [comment]
html-entries is exported from `utils/index` are you using `@faire/mjml-react/utils` anywhere in your package?
Otherwise your build might be picking it up from the utils index

**Comment by emmclaughlin** [comment]
Every component uses `@faire/mjml-react/utils` as they rely on this function: https://github.com/Faire/mjml-react/blob/main/src/utils/mjml-component-utils.ts#L9 and then the re-export includes html-entities https://github.com/Faire/mjml-react/blob/main/src/utils/index.ts#L1

I think we need to fix [this line ](https://github.com/Faire/mjml-react/blob/main/src/utils/html-entities.ts#L1) to be an import statement instead of require. Right now it compiles to `require` in esm. I'll look at putting up a fix today.

**Comment by emmclaughlin** [comment]
@kasapvictor this [PR](https://github.com/Faire/mjml-react/pull/98) should fix the issue. Please upgrade to v3.1.2 and try again

**Comment by kasapvictor** [comment]
@emmclaughlin 
Oh my God, you made it so fast, it's unbelievable =) Thank you again.

**Comment by kasapvictor** [comment]
> @kasapvictor this [PR](https://github.com/Faire/mjml-react/pull/98) should fix the issue. Please upgrade to v3.1.2 and try again

Yes! It works! 🙏🙏🙏
